### ISSUE TITLE
Use SFML instead of SDL

### ISSUE THREAD

**Issue by Salamandar** [mdsitton/musicgame#3]
Hi there !
I've been told about SFML. This other media API is way faster and, some say, easier to use.
It supports all systems.

What do you think about it ?

**Comment by Salamandar** [comment]
A benchmark (you'll laugh) : http://en.sfml-dev.org/forums/index.php?topic=43.0

**Comment by mdsitton** [comment]
So first this project is using only opengl, so all SDL is really being used for a this point is its window/opengl context creation, and os event abstraction code. Which using sdl2 here will effect the performance hardly any. There are a few downsides to sdl2 on certain plaforms, but I plan on slowly writing native backends for various platforms probably starting with windows. (This wont be for a long while though) 

Second look later on in that thread:
http://en.sfml-dev.org/forums/index.php?topic=43.msg81142#msg81142
(amusing thing is my slow opengl python font rendering on another project is ~50% faster than the sdl2 font rendering in that benchmark.)

Nowadays sdl and sfml largely have similar performance...

The reason the old benchmark was so slow, because back with SDL 1.2, it was using a software renderer. Today however SDL2 has several rendering backends for its apis, OpenGL, Software, and Direct3D.

So if you look here you will see the supported SDL2 platforms:
https://wiki.libsdl.org/SDL_SysWMinfo
Windows Win32
Windows WinRT ("Modern" application, Windows Phone, etc.)
Linux - X11
Linux - Wayland
Linux - Mir
Mac OS X
iOS
Anrdoid

vs current SFML supported platforms:
Windows Win32
Linux X11
Mac OS X

future platforms:
iOS
Android

As far as i know SMFL only supports OpenGL where as SDL2 supports the following graphics api's as far as I understand:
Direct3D
OpenGL
OpengGL ES

And it can be fairly easily hacked to use other graphics api's such as this example for amd's mantle:
https://github.com/Overv/MantleHelloTriangle

So to me I see a clear advantage for SDL2 over SFML.

**Comment by mdsitton** [comment]
If i were using SDL 1.2 as the original benchmark was using I would completely agree, SDL 1.2 is completely terrible in every way. They really turned things around with sdl2.

**Comment by Salamandar** [comment]
Hmmmm okay, I trust you on this.
And SDL2 supports Wayland, so I choose this xD

**Comment by mdsitton** [comment]
haha yeah I have yet to try it on wayland should be interesting though :D

**Comment by Salamandar** [comment]
Are you on Linux ? I am using Manjaro for a year now (after Ubuntu, Fedora, Mint), and THIS IS THE BEST OS EVER.
Using X though. I hope Cinnamon (my desktop) supports Wayland some day.

**Comment by mdsitton** [comment]
Well i just moved, and haven't had the time to set my desktop back up (Currently on my macbook pro)

But on my desktop I generally use Arch Linux most of the time. My preferred desktop environment is also cinnamon. (Majaro is based on Arch Linux btw)

I tried Manjaro a few years ago though. Its probably improved a lot since then though.

**Comment by Salamandar** [comment]
Yeah I know, a friend tried to make me use Arch… When I didn't know anything but Ubuntu. That was a bad idea ^^ It works pretty good, but it still feels "new and not completely stable". Enough stable for a newby :)
